### ISSUE TITLE
diHiggs projection 

### ISSUE THREAD

**Issue by jacoterh** [LHCfitNikhef/smefit_database#33]
We should update the filename of this projection such that it agrees with dataset_name:
https://github.com/LHCfitNikhef/smefit_database/blob/32bff4c9bfb88eecb676f203773e3acf3b961e96/commondata_projections_L0/ATLAS_hh_runII_13TeV.yaml#L1

**Comment by arossia94** [comment]
In fact, what makes more sense is to modify the `dataset_name` of that particular file. The file name is more accurate since the measurement is Run2 and hence at 13 TeV. All the other files with the name `ATLAS_hh_runII_13TeV.yaml` have the correct dataset name, so correcting the dataset in this one also minimizes the number of changes to do.
